### ISSUE TITLE
Kernel 3.0

### ISSUE THREAD

**Issue by dresch86** [SimpleMachines/sphinx-for-smf#12]
I have a VPS that unfortunately is still running Kernel 2.6 and Ubuntu 15.10. I see you require kernel 3.0. Is there any chance I can still get this to work?

**Comment by jdarwood007** [comment]
The kernel requirements where for the Sphinx Search.  Looking at them, they do support 2.4 and 2.6.  http://sphinxsearch.com/docs/current.html#supported-system

Not sure why now only 3.0 is listed.
