### ISSUE TITLE
Version typo in package-info.xml?

### ISSUE THREAD

**Issue by Brettflan** [SimpleMachines/sphinx-for-smf#13]
Shouldn't this line in package-info.xml for the 2.1 install refer to the "SMF 2.1" folder rather than "SMF 2.0"?
https://github.com/SimpleMachines/sphinx-for-smf/blob/master/package-info.xml#L19

Looks like a copy-paste mishap.

**Comment by jdarwood007** [comment]
Yes it should.  Fixed it.
