### ISSUE TITLE
Support Manticore alternative

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/sphinx-for-smf#22]
Manticore appears to be a fork of Sphinx and has compatibility with Sphinx.  Thus it should be possible to support Manticore

https://manticoresearch.com/about/
https://manticoresearch.com/2019/05/14/benchmark_manticore3_vs_sphinx3

**Comment by chopinesque** [comment]
Another great thing about Manticore, apart from [pseudo-sharding support and 10x faster SELECT](https://manticoresearch.com/2021/12/23/manticore-search-4-2-0-10x-faster-select-major-bugs-fixed-debian-bullseye-support/) in latest version, is that is is [fully open source](https://github.com/manticoresoftware/manticoresearch); in contrast, Sphinx only has accessible code for its [old version](https://github.com/sphinxsearch/sphinx):

> The sources for 3.0 will also be posted here when we decide to make those publicly 
available.

**Comment by jdarwood007** [comment]
Well its possible that the PR for adding Sphinx 3.0 support may support Manticore as well:
https://github.com/SimpleMachines/sphinx-for-smf/pull/23

I haven't tested Manticore yet, I haven't had time to, but if its based on the Sphinx 3.0, the changes made to support Sphinx 3.0 should support it.  In the end, I would be most likely splitting the source into 2 files, one for Sphinx and the Manticore extending the Sphinx class for now to adjust code to support it, until it becomes incompatible and needs to be its own file.

**Comment by klirichek** [comment]
Manticore is based on Sphinx 2.x branch (NOT on Sphinx 3.0 as it's sources are not open).
Also, FYI, sql_attr_timestamp (targeted by #23) is supported by manticore.

**Comment by chopinesque** [comment]
Some interesting [feedback](https://forum.manticoresearch.com/t/smf-and-manticore/976/4?u=spido):

As for the PR https://github.com/SimpleMachines/sphinx-for-smf/pull/23/files there may be problem with version detection since it says:

`preg_match('~Sphinx (\d+)\.(\d+)~i', $raw_version, $m);`		
which won’t work for Manticore. And it may be better in general not to parse indexer -v output, but run `SHOW STATUS LIKE '%version%'`, but I’m not sure it works in Sphinx 3.0.

**Comment by jdarwood007** [comment]
I added a PR that should add support.  While manticore does conversion.  I didn't test that.  I rebuilt from scratch.  So your mileage may vary on its conversion process.
