### ISSUE TITLE
Remove "Maximum # matches" from SMF config page

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/sphinx-for-smf#3]
Hi,

with https://github.com/SimpleMachines/sphinx-for-smf/commit/d294feeb849cbea2b02f2d55429987b4335cf284 the deprecated "max_matches" setting was removed from the generated config.

After this change the "Maximum # matches" setting of the SMF config page could be also removed.

**Comment by ghost** [comment]
Ok, the max_matches config entry was deprecated but the query based limit used in the plugin is still valid:

https://stackoverflow.com/questions/29391031/what-is-instead-max-matches

So closing this, nothing to do here.

**Comment by jdarwood007** [comment]
I missed that we could still use it in queries when I researched where the option went.  I added it into the query now.

**Comment by ghost** [comment]
Mhhh, but is this not already used in:

https://github.com/SimpleMachines/sphinx-for-smf/blob/bc65cbfbfa5b77957fb12f57ca35438e856a9d54/SMF%202.0/SearchAPI-Sphinxql.php#L278

**Comment by jdarwood007** [comment]
Hmm, you are correct.  However their documentation states this:

> Introduced in order to control and limit RAM usage, max_matches setting defines how much matches will be kept in RAM while searching each index. Every match found will still be processed; but only best N of them will be kept in memory and return to the client in the end. Assume that the index contains 2,000,000 matches for the query. You rarely (if ever) need to retrieve all of them. Rather, you need to scan all of them, but only choose "best" at most, say, 500 by some criteria (ie. sorted by relevance, or price, or anything else), and display those 500 matches to the end user in pages of 20 to 100 matches. And tracking only the best 500 matches is much more RAM and CPU efficient than keeping all 2,000,000 matches, sorting them, and then discarding everything but the first 20 needed to display the search results page. max_matches controls N in that "best N" amount.

From their description, by specifying the option as well reduces ram usage.  Which is a good thing on busy servers.

**Comment by ghost** [comment]
Ahh, yes. That makes sense.
